GET http://127.0.0.1:5000/userData?userId=cool-data

###

GET http://127.0.0.1:5000/anaylyzeLayers?userId=cool-data
Content-Type: image/png

###

GET http://127.0.0.1:5000/anaylyzeProtocols?userId=cool-data

###